api = "0.7"

[buildpack]
  description = "A buildpack for installing and configuring PHP"
  homepage = "https://github.com/paketo-buildpacks/php-dist"
  id = "initializ-buildpacks/php-dist"
  keywords = ["php"]
  name = "Initializ Buildpack for PHP Distribution"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/php-dist/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml", "config/default.ini", "config/buildpack.ini"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    php = "8.3.*"

  [[metadata.dependencies]]
    checksum = "sha256:23311a3918036e4187bfc95144f3f6b958f93ae04eeda28885a294b03039cea2"
    cpe = "cpe:2.3:a:php:php:8.3.6:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.3.6?checksum=39695f5bd107892e36fd2ed6b3d3a78140fd4b05d556d6c6531a921633cacb5f&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.6.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.6.tar.gz"
    source-checksum = "sha256:39695f5bd107892e36fd2ed6b3d3a78140fd4b05d556d6c6531a921633cacb5f"
    stacks = ["Initializ Distroless Stack"]
    uri = "https://artifacts.paketo.io/php/php_8.3.6_linux_x64_jammy_23311a39.tgz"
    version = "8.3.6"


  [[metadata.dependencies]]
    checksum = "sha256:fa9d48dfb71545cd93b15207ffcab5b89aa52b59110dc78ae5c910286e775ad5"
    cpe = "cpe:2.3:a:php:php:8.3.7:*:*:*:*:*:*:*"
    deprecation_date = "2026-11-23T00:00:00Z"
    id = "php"
    licenses = ["PHP-3.0", "PHP-3.01"]
    name = "PHP"
    purl = "pkg:generic/php@8.3.7?checksum=2e11d10b651459a8767401e66b5d70e3b048e446579fcdeb0b69bcba789af8c4&download_url=https://github.com/php/web-php-distributions/raw/master/php-8.3.7.tar.gz"
    source = "https://github.com/php/web-php-distributions/raw/master/php-8.3.7.tar.gz"
    source-checksum = "sha256:2e11d10b651459a8767401e66b5d70e3b048e446579fcdeb0b69bcba789af8c4"
    stacks = ["Initializ Distroless Stack"]
    uri = "https://artifacts.paketo.io/php/php_8.3.7_linux_x64_jammy_fa9d48df.tgz"
    version = "8.3.7"

  [[metadata.dependency-constraints]]
    constraint = "8.1.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.2.*"
    id = "php"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "8.3.*"
    id = "php"
    patches = 2

[[stacks]]
  id = "*"
  mixins = ["argon2", "libcurl4", "libedit", "libgd", "imagemagick", "oniguruma", "libxml2", "yaml"]

[[stacks]]
  id = "*"
